name: Create and publish a Docker image

on:
  push:
    branches: ['main']

env:
  IMAGE_NAME: lkw1211/boardgaming-front

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ secrets.REGISTRY }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ secrets.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Run shell script
        run: |
          docker build . -t ${{ secrets.REGISTRY }}/${{ env.IMAGE_NAME }}
          docker push ${{ secrets.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Deploy on OCI
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.OCI_DOMAIN }}
          username: ubuntu
          key: ${{ secrets.OCI_PRIVATE_KEY }}
          port: ${{ secrets.OCI_SSH_PORT }}
          script: |
            cd /home/ubuntu/cron
            ./deploy.sh
